### ISSUE TITLE
Update 'aima-data' submodule

### ISSUE THREAD

**Issue by utkarsh23** [aimacode/aima-julia#18]
I've noticed that the test `run-text-test.jl` fails because it cannot locate `gutenberg.txt` inside the submodule `aima-data`. This is because the `aima-data` submodule of this repository does not point to the latest commit of `aima-data` repo. We need to update that. I think only those who have complete access to this repository can update it.
Please look into this @norvig @mikhail-j

**Comment by mikhail-j** [comment]
@utkarsh23 @norvig  I checked `run_text_tests.jl` and the relative path for `gutenberg.txt` is the most recent (`./aima-data/gutenberg.txt` [9ba0497](https://github.com/aimacode/aima-data/commit/9ba049710614d28af50bafc34f2844e684356127)).

If you look at [run_travis_tests.sh](https://github.com/mikhail-j/aima-julia/blob/master/tests/run_travis_tests.sh#L18), the travis-ci build clones the aima-data repository with the latest commits.

This means that during Travis-CI testing, both `/aima-julia/aima-data` and `/aima-julia/tests/aima-data` exist.

But `/aima-julia/tests/aima-data` is used by the `Base.Test` tests in `/aima-julia/tests`.


The main reason why `/aima-julia/aima-data` exists as a git submodule is because `aima-julia` uses it to initialize the machine learning datasets for the machine learning algorithms.

As a result, the git submodule should be updated only if a dataset was moved or added.

**Comment by utkarsh23** [comment]
@mikhail-j thanks for the repsonse! Much appreciated! :smile:
